/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Main (void);
GtkWidget* create_File_Chooser (void);
GtkWidget* create_Log (void);
GtkWidget* create_About_Dialog (void);
GtkWidget* create_IOWIN (void);
GtkWidget* create_Fill_Memory (void);
