/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#include "sim.h"
#include "simglb.h"
#include "guiglb.h"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "prototypes.h"


void Show_All(void)
{
  Show_Flags();
  Show_Registers();
  Dump_From_Register(Dump_Reg);
  Show_Code(PC, FALSE);
}


int main (int argc, char *argv[])
{
  GtkWidget *Main;
  GtkBuilder      *builder; 
  GtkWidget       *window;

 int do_getfile(char *);

  gtk_set_locale ();
  gtk_init (&argc, &argv);

    builder = gtk_builder_new();
    gtk_builder_add_from_file (builder, "emugl2.glade", NULL);

    window = GTK_WIDGET(gtk_builder_get_object(builder, "window_main"));
    gtk_builder_connect_signals(builder, NULL);

    g_object_unref(builder);

//    gtk_widget_show(window);                
//    gtk_main();
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Main = create_Main ();
  gtk_widget_show (Main);

  Dump_Reg = 'P';
  init_Log(Main);
  if (do_getfile("./test/z80main.bin"))
//  if (do_getfile("./test/testops.bin"))
//  if (do_getfile("./test/testio.bin"))
//  if (do_getfile("./test/testscroll.bin"))
    return(1);

  init_Flags(Main);
  init_Registers(Main);
  init_Memory(Main);
  init_Code(Main);
  init_IOport();

  Dump_From_Register(Dump_Reg);
  Show_Flags();
  Show_Registers();
  Show_Code(PC, TRUE);

  gtk_main ();

  return 0;
}

// called when window is closed
void on_window_main_destroy()
{
    gtk_main_quit();
}
